version: '3.4'


services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"

  marry.api:
    image: ${DOCKER_REGISTRY-}marryapi
    build:
      context: .
      dockerfile: Marry.Api/Dockerfile
