version: '3.4'
networks:
   backend:

services:

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=Numsey#2022
      - ACCEPT_EULA=Y
    volumes:
      - c:\mssql:/var/opt/mssql/data
    ports:
      - "1450:1433"

  marry.api:
    image: ${DOCKER_REGISTRY-}marryapi
    build:
      context: .
      dockerfile: Marry.Api/Dockerfile

  school.api:
    image: ${DOCKER_REGISTRY-}schoolapi
    build:
      context: .
      dockerfile: School.Api/Dockerfile


  ocelotgateaway:
    image: ${DOCKER_REGISTRY-}ocelotgateaway
    build:
      context: .
      dockerfile: OcelotGateAway/Dockerfile
    ports:
     - 9090:80
    networks:
      - backend
    
  

